#!/usr/bin/env -S npx ts-node -r dotenv/config
/* eslint-disable @typescript-eslint/no-var-requires */
const doWeather = require('./dist/index.js')

doWeather.getAndDisplayTimeAndWeatherForLocationList(process.argv)
